export const muscles: string[] = [
  'Trizeps',
  'Bizeps',
  'Schulter (seitlich)',
  'Latissimus',
  'Abduktor',
  'Adduktor',
  'Gluteus Maximus',
  'Waden',
  'Deltamuskel',
  'Quadrizeps',
  'Oberschenkel',
  'Trapezmuskel',
  'Unterer Rücken',
  'Schulter (hinten)',
  'Schulter',
  'Schulter (vorne)',
  'Bauch (gerade)',
  'Bauch',
  'Bauch (schräg)',
  'Cardio',
  'Ganzkörper',
  'Rumpf',
  'Brust',
  'Brust (untere)',
  'Brust (obere)',
  'Brust (seitlich)',
  'Nacken',
  'Beinbeuger'
].sort((a, b) => a.localeCompare(b));
